### ISSUE TITLE
The 'Discuss on Twitter' button starts a search instead of creating a Tweet Web Intent

### ISSUE THREAD

**Issue by afranck64** [osscameroon/blog#8]
The 'Discuss on Twitter' button at the bottom of blog articles currently starts a search in Twitter: 
![image](https://user-images.githubusercontent.com/1263883/176042453-16ad70c5-03d3-4c77-8c56-e635578f75f7.png)
It should instead create a Tweet Web Intent for a new tweet with the article link.
e.g.

`https://twitter.com/intent/tweet?text=How to write a post on OSS Cameroon blog
 https://stage.blog.osscameroon.com/posts/how-to-write-a-post-on-oss-cameroon-blog` -->  [https://twitter.com/intent/tweet?text=How%20to%20write%20a%20post%20on%20OSS%20Cameroon%20blog%20https://stage.blog.osscameroon.com/posts/how-to-write-a-post-on-oss-cameroon-blog](https://twitter.com/intent/tweet?text=How%20to%20write%20a%20post%20on%20OSS%20Cameroon%20blog%20https://stage.blog.osscameroon.com/posts/how-to-write-a-post-on-oss-cameroon-blog)

**Comment by tericcabrel** [comment]
Thank you @afranck64 for the feedback! I will fix that.
